name: Static Analysis
on:
  push:
    branches: [main]
    paths:
      - "common-contracts/**"
      - ".github/workflows/slither.yaml"
  pull_request:
    branches: [main]
    paths:
      - "common-contracts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        node-version: [12]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Install solc
        run: |
          sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.6.12/solc-static-linux
          sudo chmod +x /usr/bin/solc
      - name: Install slither
        run: |
          python -m pip install --upgrade pip
          pip3 install slither-analyzer==0.8.1

      - name: Summary of static ananlysis
        run: |
          slither ./common-contracts/src/components/ --print human-summary
      #     slither ./common-contracts/src/interfaces --print human-summary
      #     slither ./common-contracts/src/libraries --print human-summary
      #     slither ./common-contracts/src/upgrade --print human-summary

      # - name: Contract summary of static ananlysis
      #   run: |
      #     slither ./common-contracts/src/components --print contract-summary
      #     slither ./common-contracts/src/interfaces --print contract-summary
      #     slither ./common-contracts/src/libraries --print contract-summary
      #     slither ./common-contracts/src/upgrade --print contract-summary

      # - name: Function summary
      #   run: |
      #     slither ./common-contracts/src/components --print function-summary
      #     slither ./common-contracts/src/interfaces --print function-summary
      #     slither ./common-contracts/src/libraries --print function-summary
      #     slither ./common-contracts/src/upgrade --print function-summary

      # - name: Inheritance
      #   run: |
      #     slither ./common-contracts/src/components --print inheritance
      #     slither ./common-contracts/src/interfaces --print inheritance
      #     slither ./common-contracts/src/libraries --print inheritance
      #     slither ./common-contracts/src/upgrade --print inheritance

      # - name: Data dependency
      #   run: |
      #     slither ./common-contracts/src/components --print data-dependency
      #     slither ./common-contracts/src/interfaces --print data-dependency
      #     slither ./common-contracts/src/libraries --print data-dependency
      #     slither ./common-contracts/src/upgrade --print data-dependency
